default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: key_lime_api_database_development

test:
  <<: *default
  database: key_lime_api_database_test

production:
  <<: *default
  database: key_lime_api_database_production
